version: '3.9'

services:
  crypto_api:
    container_name: crypto_api
    build:
      context: .
      dockerfile: ./api_crypto/web.Dockerfile
    working_dir: /code
    volumes:
      - ./:/code
    depends_on:
      - redis
    ports:
      - 8080:8080
    environment:
      - WATCHFILES_FORCE_POLLING=true
    restart: always
    networks:
      - crypto_telethon_net

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - crypto_telethon_net

  celery_worker:
    build:
      context: .
      dockerfile: ./api_telegram/Dockerfile
    image: celery_worker
    command: /start-celeryworker
    volumes:
      - .:/code
    restart: always
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - crypto_telethon_net

  celery_beat:
    build:
      context: .
      dockerfile: ./api_telegram/Dockerfile
    image: celery_beat
    command: /start-celerybeat
    volumes:
      - .:/code
    restart: always
    depends_on:
      - redis
      - celery_worker
    env_file:
      - .env
    networks:
      - crypto_telethon_net

  celery_flower:
    build:
      context: .
      dockerfile: ./api_telegram/Dockerfile
    image: celery_flower
    command: /start-flower
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - 5557:5555
    restart: always
    depends_on:
      - redis
      - celery_worker
    networks:
      - crypto_telethon_net

networks:
  crypto_telethon_net:
    name: cr_tel_net
    driver: bridge