#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A tasks inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 5
done
>&2 echo 'Celery workers is available'

rm -f './celerybeat.pid'

celery -A tasks beat --max-interval 10800
